;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cycle-spacing
	forward-sexp
	org-beginning-of-line
	org-edit-src-save
	org-end-of-line
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	))
